taskadapter/redmine-java-api

src/main/java/com/taskadapter/redmineapi/CustomFieldManager.java
src/main/java/com/taskadapter/redmineapi/RedmineManager.java
src/main/java/com/taskadapter/redmineapi/bean/CustomFieldDefinition.java
src/main/java/com/taskadapter/redmineapi/bean/CustomFieldDefinitionFactory.java
src/main/java/com/taskadapter/redmineapi/internal/RedmineJSONParser.java
src/main/java/com/taskadapter/redmineapi/internal/Transport.java
src/main/java/com/taskadapter/redmineapi/internal/URIConfigurator.java
src/test/java/com/taskadapter/redmineapi/CustomFieldDefinitionsTest.java
src/test/resources/custom_fields.json

The attached changes utilize the custom_field-api created by http://www.redmine.org/issues/9664 to retrieve the field definitions from the redmine instance.
The existing unittest still work, two new unittests verify the new functionality.

Implement retrieving custom field definitions

---

src/main/java/com/taskadapter/redmineapi/internal/RedmineJSONBuilder.java
src/test/java/com/taskadapter/redmineapi/IssueManagerTest.java

While working on netbeans redmine integration, I noticed, that I failed to change the project for an issue. I could track it down to using the project identifier, instead of the id of the project when creating the request object.
I created a unittest, that demonstrates the problem and verifies the fix.
The fix is intended to support the "old" way and the new way - the idea: As long a project ID is present, use that, if it is not present, fall back to the identifier. All unittests still pass.

Fix setting project on existing issue

---

src/main/java/com/taskadapter/redmineapi/IssueManager.java

The javadoc of `IssueManager.createIssue()`was deprecated. The sample code does not work anymore, since `IssueFactory.create()` has changed.

Updated deprecated javadoc.

---

src/main/java/com/taskadapter/redmineapi/internal/RedmineJSONBuilder.java
src/test/java/com/taskadapter/redmineapi/internal/RedmineJSONGeneratorTest.java

With this fix, it is now possible to add or change custom field values on a Redmine version

Add custom fields to the version JSON writer, add unit test

---

build.gradle
src/main/java/com/taskadapter/redmineapi/internal/Transport.java

also removed explicit dependency on Apache HttpCore:
that library is referenced in HttpClient's pom.xml file anyway.
fixed one place in Transport.java where they changed the API,
everything else looks fine. existing tests pass.

Issue #212. Updated Apache HttpClient dependency to v. 4.5.1

---

build.gradle
src/test/java/com/taskadapter/redmineapi/AttachmentIntegrationTest.java
src/test/java/com/taskadapter/redmineapi/CustomFieldDefinitionsTest.java
src/test/java/com/taskadapter/redmineapi/IssueManagerTest.java
src/test/java/com/taskadapter/redmineapi/MembershipManagerTest.java
src/test/java/com/taskadapter/redmineapi/ParentProjectTest.java
src/test/java/com/taskadapter/redmineapi/ProjectIntegrationTest.java
src/test/java/com/taskadapter/redmineapi/ProjectsTest.java
src/test/java/com/taskadapter/redmineapi/RedmineManagerTest.java
src/test/java/com/taskadapter/redmineapi/UserIntegrationTest.java
src/test/java/com/taskadapter/redmineapi/WikiManagerTest.java
src/test/java/com/taskadapter/redmineapi/bean/IssueTest.java
src/test/java/com/taskadapter/redmineapi/bean/UserTest.java
src/test/java/com/taskadapter/redmineapi/internal/RedmineDateParserTest.java
src/test/java/com/taskadapter/redmineapi/internal/RedmineJSONParserTest.java

AssertJ is a successor of fest-assert, which seems to be abandoned.

 Issue #227. switch from Fest-assert library to AssertJ

---

src/main/java/com/taskadapter/redmineapi/internal/Transport.java
src/main/java/com/taskadapter/redmineapi/internal/URIConfigurator.java
src/test/java/com/taskadapter/redmineapi/AttachmentIntegrationTest.java
src/test/java/com/taskadapter/redmineapi/IntegrationTestHelper.java

Fix for #121  download attachments using API access key

---

build.gradle
src/main/java/com/taskadapter/redmineapi/bean/Assignee.java
src/main/java/com/taskadapter/redmineapi/bean/GenericAssignee.java
src/main/java/com/taskadapter/redmineapi/bean/GenericAssigneeFactory.java
src/main/java/com/taskadapter/redmineapi/bean/Group.java
src/main/java/com/taskadapter/redmineapi/bean/Issue.java
src/main/java/com/taskadapter/redmineapi/bean/IssueCategory.java
src/main/java/com/taskadapter/redmineapi/bean/User.java
src/main/java/com/taskadapter/redmineapi/internal/RedmineJSONParser.java
src/test/java/com/taskadapter/redmineapi/IssueManagerTest.java
src/test/java/com/taskadapter/redmineapi/bean/AssigneeTest.java
src/test/java/com/taskadapter/redmineapi/internal/RedmineJSONParserTest.java
src/test/resources/issue/issue_with_assignee.json
src/test/resources/issue_categories.json

- New interface Assignee implemented by User and Group
- change "assigne" attribute of Issue and IssueCategory to Assignee
- add a GenericAssignee implementing Assigne to handle return values
that don't indicate whether a User or Group is returned
This is a transplantation of the changes against the updated master branch from the pre-JDK8 branch.
This is based on the comments in issue 213.

Allow issue/catory assignment to users and groups

---

src/test/java/com/taskadapter/redmineapi/IssueManagerTest.java

This is a followup to PR #231. There are two problems with the test:
1. the test system needs to have group assignment enabled (this was not the case)
2. the groups need to have project memberships to be assignable
I adjusted the first problem in the test system, the second is addressed in this
change. With both changes done all tests pass.

Add missing project memberships for test group (fix failing unittest)

---

src/main/java/com/taskadapter/redmineapi/IssueManager.java
src/main/java/com/taskadapter/redmineapi/TimeEntryManager.java
src/main/java/com/taskadapter/redmineapi/UserManager.java
src/main/java/com/taskadapter/redmineapi/internal/DirectObjectsSearcher.java
src/main/java/com/taskadapter/redmineapi/internal/ResultsWrapper.java
src/main/java/com/taskadapter/redmineapi/internal/Transport.java
src/test/java/com/taskadapter/redmineapi/IssueManagerIT.java
src/test/java/com/taskadapter/redmineapi/TimeEntryManagerIT.java
src/test/java/com/taskadapter/redmineapi/UserIT.java

Relates to #259 
The only thing I dislike is to keep short name for deprecated method: e.g `getTimeEntries()` vs `getTimeEntriesResultsWrapper()`. Commits like 682e8a614006753ae809455baa56f1c1d6ff3f6e simply remove old methods `getAssignee()` with new ones `getAssigneeName()` and `getAssigneeId()` but I want to ask before propose a break in compatibility.
Even more I don't know if a single commit is preferred.
I can rebase and squash after code review

Results wrapper

---

src/main/java/com/taskadapter/redmineapi/bean/Membership.java
src/main/java/com/taskadapter/redmineapi/internal/RedmineJSONBuilder.java
src/main/java/com/taskadapter/redmineapi/internal/RedmineJSONParser.java
src/test/java/com/taskadapter/redmineapi/IssueManagerIT.java
src/test/java/com/taskadapter/redmineapi/MembershipManagerIT.java

This is the result of moving redminenb to the new major version of redmine-java-api.
Most changes are very smooth and work quite good. These two changesets address two issues:
- Memberships are used to enumerate Users per project in redminenb, so I used the Memberships directly in the past, as these already contain the necessary data (the id and name of the group/user). In the current incarnation this information is discarded by the bindings. With this changeset the names of the groups and users are extracted from the reply
- The two attributes category and and targetVersion could not be unset - the null value was discarded from the updateset. This is attributed in the second changeset by introducing a generic setter for "Identifiable" attribute values.
Please note: The first change was …

Allow setting TargetVersion+Category to null / access names from Memberships

---

src/main/java/com/taskadapter/redmineapi/RedmineManager.java

In order to allow writing our own custom requests (in the case the API has been improved by custom development), why not exporting the Transport?
We could then write our own requests like this:
```java
RedmineManager redmineManager = RedmineManagerFactory.createWithApiKey(..., ...);
Transport transport = redmineManager.getTransport();
transport.getObject(..., ...);
```

Allow writing our own custom requests

---

src/main/java/com/taskadapter/redmineapi/bean/WikiPageDetail.java
src/main/java/com/taskadapter/redmineapi/internal/RedmineJSONBuilder.java
src/main/java/com/taskadapter/redmineapi/internal/RedmineJSONParser.java
src/test/java/com/taskadapter/redmineapi/WikiManagerIT.java
src/test/java/com/taskadapter/redmineapi/bean/AttachmentsTest.java

Continue from issue #314 
Problem was not only in renaming json key.
Attachments were never sent. `RedmineJSONBuilder` didn't have any attachments processing.
Added test for JSON object check. Also tested on the real redmine

Wiki attachments

---

src/main/java/com/taskadapter/redmineapi/bean/Project.java
src/main/java/com/taskadapter/redmineapi/internal/RedmineJSONBuilder.java
src/main/java/com/taskadapter/redmineapi/internal/RedmineJSONParser.java
src/test/java/com/taskadapter/redmineapi/ProjectIntegrationIT.java

There is a related PR #308, that is too old and not merged yet. This PR allows obtaining the STAUS of a project. There are no new tests, instead the status check is added to existing tests.
Note1: Redmine api does not allow reopen, close or archive projects. So as, Project.setStatus has only effect on the project bean, but it does not change the status in the redmine database. An issue was been recorded about this (documented in the code).
Note 2: But we still need setStatus as RedmineJSONParser needs it. A solution to avoid creating this setter could be use storage.set instead result.setStatus, but it is not possible as storage.set is not visible from RedmineJSONParser

Add getter for project status

---

src/main/java/com/taskadapter/redmineapi/bean/Project.java
src/main/java/com/taskadapter/redmineapi/internal/RedmineJSONBuilder.java
src/main/java/com/taskadapter/redmineapi/internal/json/JsonOutput.java
src/test/java/com/taskadapter/redmineapi/ProjectIntegrationIT.java

Fixes #318.
Cause: Trackers are not updated in the server because RedmineJSONBuilder.writeProject sends a collection of Tracker objects to redmine server. However the api requires an array of tracker ids.
Solution: Writing trackers uses JsonOutput.addScalarArray wich replaces JsonOutput.addArrayIfNotNull.
But this still does not solve the problem, as in the case of a new project, an empty array of trackers would be sent to the server. Therefore any default tracker configured in the server would be overridden, and the project be created without trackers.
To avoid this, now the Project constructor does not initialize the storage for TRACKERS (initializations are made in project’s getters and setters that manage trackers). An additional method to clear all trackers has been added.

Update project trackers on redmine server

---

build.gradle

Hi, the current version of the library conflicts with the new version that is installed in the transitive library, we had to update the version.

changed org.json:json dependency: version 20090211 -> 20190722

---

src/main/java/com/taskadapter/redmineapi/RedmineManagerFactory.java
src/main/java/com/taskadapter/redmineapi/internal/Transport.java
src/main/java/com/taskadapter/redmineapi/internal/URIConfigurator.java
src/main/java/com/taskadapter/redmineapi/internal/comm/redmine/RedmineApiKeyAuthenticator.java
src/main/java/com/taskadapter/redmineapi/internal/comm/redmine/RedmineUserPasswordAuthenticator.java
src/test/java/com/taskadapter/redmineapi/IssueManagerIT.java

this change moves API access key from URIs (which can be logged,
thus violating security rules) to http request headers.

#338 move API access key from URIs to http headers

---

README.md

Hi @alexeyOnGitHub, I've updated the two last examples of README.md (for additional CAs and for Client Certificate authentication) to a couple of useful snippets. I left the original examples (that are basically what the Test class uses) so users have an additional place to look for usage tips.

Updated README.md certificate connection examples 

---

CHANGELOG.md
build.gradle
src/main/java/com/taskadapter/redmineapi/internal/comm/TransportDecoder.java
src/test/java/com/taskadapter/redmineapi/IssueManagerIT.java
src/test/resources/api_test.properties

Redmine 4 returns an empty response for at least some "Delete" calls,
and the library did not know how to handle those. I added null entity handling in TransportDecoder.

support Redmine 4 "delete object" empty responses.

---

CHANGELOG.md
src/main/java/com/taskadapter/redmineapi/bean/IssueRelation.java
src/main/java/com/taskadapter/redmineapi/internal/RedmineJSONBuilder.java
src/main/java/com/taskadapter/redmineapi/internal/RedmineJSONParser.java

Redmine 4 has a backward incompatible change in its Issue Relations REST API: it now requires "issue_to_id" parameter
to be a comma-separated string when creating issue relations (instead of previous single number).
this change adds support for the new format. I tested this with both Redmine 3.4.5 and 4.2.0.

support Redmine 4 new "issue relation" format
